### PR TITLE
✏️ Fix typo in syntax for using the GitHub Action tag directly (instead of with Docker) in README

### PR DESCRIPTION
**Pull request by art049**
It seems that github action uses `@` instead of `:` to define the version.

### CODE REVIEW

**Comment by tswfi** [comment]
Just added this action to a project and the current readme is right with ":". @ doesn't work.

**Comment by art049** [comment]
This fix was intended for the use of the non dockerized version.
In this case `- uses: tiangolo/latest-changes:0.0.3` didn't work as "pure" github actions uses `@`
But it worked fine for the dockerized one like this: ` - uses: docker://tiangolo/latest-changes:0.0.3`
Maybe github allows `:` as well now

**Comment by tswfi** [comment]
Oh, my bad then.

**Comment by KVROHITH098** [comment]
@tswfi Close this request it is over!

**Comment by KVROHITH098** [comment]
@tiangolo pls close this change thank you.

**Comment by tiangolo** [comment]
Thank you @art049! 🙇 ☕

**Pull request merged**
